# Generated by Django 5.2.17 on 2026-08-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
                ('device_type', models.CharField(choices=[('computer', 'Komputer'), ('laptop', 'Laptop'), ('server', 'Serwer'), ('printer', 'Drukarka'), ('router', 'Router'), ('switch', 'Switch'), ('mobile', 'Urządzenie mobilne'), ('other', 'Inne')], default='computer', max_length=20, verbose_name='typ urządzenia')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adres IP')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='adres MAC')),
                ('operating_system', models.CharField(blank=True, max_length=120, verbose_name='system operacyjny')),
                ('assigned_user', models.CharField(blank=True, max_length=120, verbose_name='użytkownik / właściciel')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='dział')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='lokalizacja')),
                ('importance', models.CharField(choices=[('low', 'Niski'), ('standard', 'Standardowy'), ('high', 'Wysoki'), ('critical', 'Krytyczny')], default='standard', max_length=20, verbose_name='poziom ważności')),
                ('monitoring_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Nieznany'), ('disabled', 'Wyłączone z monitoringu')], default='unknown', max_length=20, verbose_name='status monitoringu')),
                ('network_access_status', models.CharField(choices=[('connected', 'Przyłączone'), ('disconnected_admin', 'Odłączone administracyjnie'), ('pending_disconnect', 'Oczekuje na odłączenie'), ('pending_connect', 'Oczekuje na przyłączenie'), ('command_error', 'Błąd wykonania polecenia')], default='connected', max_length=30, verbose_name='status dostępu do sieci')),
                ('monitoring_enabled', models.BooleanField(default=True, verbose_name='monitoring włączony')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='data ostatniego sprawdzenia')),
                ('last_admin_command_at', models.DateTimeField(blank=True, null=True, verbose_name='data ostatniego polecenia administracyjnego')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
            ],
            options={
                'verbose_name': 'Urządzenie',
                'verbose_name_plural': 'Urządzenia',
                'ordering': ['name'],
            },
        ),
    ]
