# Generated by Django 5.2.17 on 2026-08-07 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='disconnect_blocked',
            field=models.BooleanField(default=False, verbose_name='ochrona przed odłączeniem (komponent kluczowy dla aplikacji)'),
        ),
        migrations.CreateModel(
            name='AdminCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('disconnect', 'Odłączenie od sieci'), ('connect', 'Przyłączenie do sieci')], max_length=20, verbose_name='rodzaj polecenia')),
                ('justification', models.TextField(verbose_name='uzasadnienie')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje na wykonanie'), ('running', 'W trakcie'), ('done', 'Wykonano'), ('failed', 'Niepowodzenie'), ('cancelled', 'Anulowano')], default='pending', max_length=20, verbose_name='status wykonania')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='data zlecenia')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='data zakończenia')),
                ('result_message', models.TextField(blank=True, verbose_name='wynik')),
                ('error_message', models.TextField(blank=True, verbose_name='komunikat błędu')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_commands', to=settings.AUTH_USER_MODEL, verbose_name='administrator zlecający')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_commands', to='devices.device', verbose_name='urządzenie')),
            ],
            options={
                'verbose_name': 'Polecenie administracyjne',
                'verbose_name_plural': 'Polecenia administracyjne',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='data sprawdzenia')),
                ('is_available', models.BooleanField(verbose_name='urządzenie dostępne')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='czas odpowiedzi (ms)')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='komunikat błędu')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_results', to='devices.device', verbose_name='urządzenie')),
            ],
            options={
                'verbose_name': 'Wynik monitoringu',
                'verbose_name_plural': 'Wyniki monitoringu',
                'ordering': ['-checked_at'],
            },
        ),
    ]
