# Generated by Django 5.2.17 on 2026-08-11 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_disconnect_blocked_admincommand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(max_length=64, verbose_name='podsieć')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='data rozpoczęcia')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='data zakończenia')),
                ('status', models.CharField(choices=[('running', 'W trakcie'), ('done', 'Zakończone'), ('failed', 'Niepowodzenie')], default='running', max_length=20, verbose_name='status')),
                ('hosts_found', models.JSONField(blank=True, default=list, verbose_name='wykryte hosty')),
                ('error_message', models.TextField(blank=True, verbose_name='komunikat błędu')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_scans', to=settings.AUTH_USER_MODEL, verbose_name='administrator')),
            ],
            options={
                'verbose_name': 'Skanowanie sieci',
                'verbose_name_plural': 'Skanowania sieci',
                'ordering': ['-started_at'],
            },
        ),
    ]
