# Generated by Django 5.2.17 on 2026-08-13 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='nazwa użytkownika')),
                ('action_type', models.CharField(choices=[('login', 'Logowanie'), ('login_failed', 'Nieudane logowanie'), ('logout', 'Wylogowanie'), ('user_created', 'Utworzenie użytkownika'), ('device_created', 'Dodanie urządzenia'), ('device_updated', 'Edycja urządzenia'), ('device_deleted', 'Usunięcie urządzenia'), ('device_disconnected', 'Odłączenie urządzenia od sieci'), ('device_connected', 'Przyłączenie urządzenia do sieci'), ('alert_status_changed', 'Zmiana statusu alertu'), ('settings_changed', 'Zmiana ustawień')], db_index=True, max_length=30, verbose_name='rodzaj operacji')),
                ('description', models.TextField(verbose_name='opis')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adres IP użytkownika')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'Działanie użytkownika',
                'verbose_name_plural': 'Działania użytkowników',
                'ordering': ['-created_at'],
            },
        ),
    ]
