# Generated by Django 5.2.17 on 2026-08-10 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_device_disconnect_blocked_admincommand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Utworzono'), ('status_changed', 'Zmiana statusu'), ('note_added', 'Dodano notatkę'), ('assigned', 'Przypisano osobę'), ('resolved', 'Rozwiązano')], max_length=20, verbose_name='rodzaj akcji')),
                ('description', models.TextField(verbose_name='opis zmiany')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data akcji')),
            ],
            options={
                'verbose_name': 'Historia alertu',
                'verbose_name_plural': 'Historie alertów',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='treść notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data dodania')),
            ],
            options={
                'verbose_name': 'Notatka do alertu',
                'verbose_name_plural': 'Notatki do alertów',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('rule_type', models.CharField(choices=[('failed_login', 'Wielokrotne nieudane logowanie'), ('critical_event', 'Zdarzenie krytyczne'), ('admin_login', 'Logowanie administratora'), ('device_unavailable', 'Niedostępność urządzenia krytycznego'), ('outside_hours', 'Logowanie poza godzinami pracy'), ('service_stopped', 'Zatrzymanie ważnej usługi'), ('repeated_errors', 'Powtarzające się błędy z urządzenia')], max_length=30, verbose_name='typ reguły')),
                ('threshold', models.PositiveIntegerField(default=5, verbose_name='próg wystąpień')),
                ('time_window_minutes', models.PositiveIntegerField(default=10, verbose_name='przedział czasowy (minuty)')),
                ('severity', models.CharField(choices=[('info', 'Informacyjny'), ('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki'), ('critical', 'Krytyczny')], default='medium', max_length=20, verbose_name='poziom zagrożenia alertu')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
            ],
            options={
                'verbose_name': 'Reguła bezpieczeństwa',
                'verbose_name_plural': 'Reguły bezpieczeństwa',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nazwa')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('severity', models.CharField(choices=[('info', 'Informacyjny'), ('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki'), ('critical', 'Krytyczny')], max_length=20, verbose_name='poziom zagrożenia')),
                ('status', models.CharField(choices=[('new', 'Nowy'), ('in_progress', 'W analizie'), ('resolved', 'Rozwiązany'), ('false_positive', 'Fałszywy alarm'), ('ignored', 'Zignorowany')], db_index=True, default='new', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='data rozwiązania')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL, verbose_name='osoba odpowiedzialna')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device', verbose_name='urządzenie')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerty',
                'ordering': ['-created_at'],
            },
        ),
    ]
