# Generated by Django 5.2.17 on 2026-08-10 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='related_logs',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='logs.logentry', verbose_name='powiązane logi'),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='alerts.alert', verbose_name='alert'),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_history_actions', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik'),
        ),
        migrations.AddField(
            model_name='alertnote',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='alerts.alert', verbose_name='alert'),
        ),
        migrations.AddField(
            model_name='alertnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_notes', to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='alert',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.securityrule', verbose_name='reguła'),
        ),
    ]
