# Generated by Django 5.2.17 on 2026-08-10 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_device_disconnect_blocked_admincommand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(db_index=True, verbose_name='czas zdarzenia')),
                ('received_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='czas odbioru')),
                ('source', models.CharField(db_index=True, max_length=100, verbose_name='źródło')),
                ('user', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='użytkownik')),
                ('event_type', models.CharField(db_index=True, max_length=100, verbose_name='typ zdarzenia')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Informacja'), ('warning', 'Ostrzeżenie'), ('error', 'Błąd'), ('critical', 'Krytyczny')], db_index=True, max_length=20, verbose_name='poziom')),
                ('message', models.TextField(verbose_name='treść komunikatu')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='dane dodatkowe (JSON)')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='devices.device', verbose_name='urządzenie')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logi',
                'ordering': ['-event_time'],
            },
        ),
    ]
